/*
 * This source file was generated by the Gradle 'init' task
 */
package org.project;

import org.project.pages.login.LoginPage;
import org.project.pages.register.RegisterPage;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

public class App {
    public static void main(String[] args) {

        JFrame frame = new JFrame("App");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(800, 600);
        frame.setMinimumSize(new Dimension(500, 400));
        frame.addComponentListener(
                new ComponentAdapter() {
                    @Override
                    public void componentResized(ComponentEvent e){
                        int w = frame.getWidth();
                        int h = frame.getHeight();
                        frame.setTitle(w+"x"+h);
                        frame.revalidate();
                        frame.repaint();
                    }
                }
        );
        CardLayout cardLayout = new CardLayout();
        JPanel cardPanel = new JPanel(cardLayout);

        LoginPage loginPage = new LoginPage(frame,cardLayout,cardPanel);
        RegisterPage registerPage = new RegisterPage(frame,cardLayout,cardPanel);

        cardPanel.add(loginPage, "loginPage");
        cardPanel.add(registerPage, "registerPage");

        frame.add(cardPanel);

        frame.setVisible(true);
    }
}





