/*
 * This source file was generated by the Gradle 'init' task
 */
package org.project;

import org.project.gui.frames.Entry;

import javax.swing.*;

public class App {
    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Entry();
            }
        });
    }
}





